// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "extensions.zotero.enable": boolean;
      "extensions.zotero.tags": string;
      "extensions.zotero.languages": string;
      "extensions.zotero.papersgptState": string;
      "extensions.zotero.startLocalServer": boolean;
      "extensions.zotero.email": string;
      "extensions.zotero.token": string;
      "extensions.zotero.isLicenseActivated": boolean;
      "extensions.zotero.grade": string;
      "extensions.zotero.supportedLLMs": string;
      "extensions.zotero.usingLanguage": string;
      "extensions.zotero.usingPublisher": string;
      "extensions.zotero.usingModel": string;
      "extensions.zotero.usingAPIKEY": string;
      "extensions.zotero.usingAPIURL": string;
      "extensions.zotero.openaiApiKey": string;
      "extensions.zotero.geminiApiKey": string;
      "extensions.zotero.claudeApiKey": string;
      "extensions.zotero.customModelApiUrl": string;
      "extensions.zotero.customModelApiKey": string;
      "extensions.zotero.customModelApiModel": string;
      "extensions.zotero.secretKey": string;
      "extensions.zotero.model": string;
      "extensions.zotero.api": string;
      "extensions.zotero.prompts": string;
      "extensions.zotero.temperature": string;
      "extensions.zotero.deltaTime": number;
      "extensions.zotero.width": string;
      "extensions.zotero.tagsMore": string;
      "extensions.zotero.chatNumber": number;
      "extensions.zotero.relatedNumber": number;
      "extensions.zotero.embeddingBatchNum": number;
    };
  }
}
